### ISSUE TITLE
Question about frequency of monopile wind turbine

### ISSUE THREAD

**Issue by whr1023** [IEAWindTask37/IEA-22-280-RWT#100]
Hi, 

I have encountered some challenges while trying to replicate the frequency of the IEA 22MW monopile wind turbine.

Specifically, I downloaded the monopile folders from GitHub and found that the modeling of the monopile only considers the foundation at the mudline (-34 m) in the SubDyn.dat file. I used OpenFAST to obtain the 1st F-A and 1st S-S frequencies of the monopile wind turbine, which are both 0.16 Hz, consistent with the report in Table 13.

However, the descriptions in the report suggest that the 0.16 Hz frequency corresponds to the monopile at -79 m, not at the mudline (-34 m). I attempted to model the monopile at -79 m, and the resulting frequency was 0.15 Hz.

Therefore, my question is whether I have made an error in my process, or if the 0.16 Hz frequency is indeed for the monopile at the mudline.

Best regards,
Haoran Wang

**Comment by gbarter** [comment]
You cannot extend the monopile from the mudline to -79m and rerun OpenFAST, because that does not appropriately capture the boundary conditions for the length that is embeded in the soil.  OpenFAST does not have a soil module (although one might be coming soon), so the current best practice is to model the monopile as a clamped boundary condition at the mudline.

**Comment by whr1023** [comment]
> 您无法将单桩从泥线延伸至 -79m 并重新运行 OpenFAST，因为这样无法正确捕获嵌入土壤的长度的边界条件。OpenFAST 没有土壤模块（尽管可能很快就会推出），因此当前的最佳做法是将单桩建模为泥线处的夹紧边界条件。

Thanks for your reply. I appericate it very much.

Best regards,
Haoran
